apiVersion: apps/v1
kind: Deployment
metadata:
  name: biztree
  namespace: esquire
  labels:
    app: biztree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: biztree
  template:
    metadata:
      labels:
        app: biztree
    spec:
      containers:
        - name: biztree
          image: esquire/biztree:latest
          imagePullPolicy: Never
          command: ["java", "-jar", "app.jar"]
          ports:
            - containerPort: 3002
          env:
            - name: BIZTREE_PORT
              value: "3002"
            - name: LOG_LEVEL_ROOT
              valueFrom:
                configMapKeyRef:
                  name: esq-config
                  key: LOG_LEVEL_ROOT
            - name: LOG_LEVEL_SF
              valueFrom:
                configMapKeyRef:
                  name: esq-config
                  key: LOG_LEVEL_SF
            - name: LOG_LEVEL_MIR0N
              valueFrom:
                configMapKeyRef:
                  name: esq-config
                  key: LOG_LEVEL_MIR0N
            - name: DB_BIZTREE_VENDOR
              value: "dev-postgres"
            - name: DB_BIZTREE_HOST
              value: "postgres-external"
            - name: DB_BIZTREE_PORT
              value: "5432"
            - name: DB_BIZTREE_NAME
              valueFrom:
                configMapKeyRef:
                  name: esq-config
                  key: POSTGRES_DB
            - name: DB_BIZTREE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: esq-config
                  key: POSTGRES_USER
            - name: DB_BIZTREE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esq-secrets
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: biztree
  namespace: esquire
spec:
  selector:
    app: biztree
  ports:
    - port: 3002
      targetPort: 3002
