apiVersion: apps/v1
kind: Deployment
metadata:
  name: keysmith
  namespace: esquire
  labels:
    app: keysmith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keysmith
  template:
    metadata:
      labels:
        app: keysmith
    spec:
      containers:
        - name: keysmith
          image: esquire/keysmith:latest
          imagePullPolicy: Never
          command: ["java", "-jar", "app.jar"]
          ports:
            - containerPort: 3005
          env:
            - name: KEYSMITH_PORT
              value: "3005"
            - name: LOG_LEVEL_ROOT
              valueFrom:
                configMapKeyRef:
                  name: esq-config
                  key: LOG_LEVEL_ROOT
            - name: LOG_LEVEL_SF
              valueFrom:
                configMapKeyRef:
                  name: esq-config
                  key: LOG_LEVEL_SF
            - name: LOG_LEVEL_MIR0N
              valueFrom:
                configMapKeyRef:
                  name: esq-config
                  key: LOG_LEVEL_MIR0N
            - name: DB_KEYSMITH_VENDOR
              value: "dev-postgres"
            - name: DB_KEYSMITH_HOST
              value: "postgres-external"
            - name: DB_KEYSMITH_PORT
              value: "5432"
            - name: DB_KEYSMITH_NAME
              valueFrom:
                configMapKeyRef:
                  name: esq-config
                  key: POSTGRES_DB
            - name: DB_KEYSMITH_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: esq-config
                  key: POSTGRES_USER
            - name: DB_KEYSMITH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esq-secrets
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: keysmith
  namespace: esquire
spec:
  selector:
    app: keysmith
  ports:
    - port: 3005
      targetPort: 3005
