apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman
  namespace: esquire
  labels:
    app: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
        - name: pacman
          image: esquire/pacman:latest
          imagePullPolicy: Never
          command: ["java", "-jar", "app.jar"]
          ports:
            - containerPort: 3004
          env:
            - name: PACMAN_PORT
              value: "3004"
            - name: LOG_LEVEL_ROOT
              valueFrom:
                configMapKeyRef:
                  name: esq-config
                  key: LOG_LEVEL_ROOT
            - name: LOG_LEVEL_SF
              valueFrom:
                configMapKeyRef:
                  name: esq-config
                  key: LOG_LEVEL_SF
            - name: LOG_LEVEL_MIR0N
              valueFrom:
                configMapKeyRef:
                  name: esq-config
                  key: LOG_LEVEL_MIR0N
            - name: DB_PACMAN_VENDOR
              value: "dev-postgres"
            - name: DB_PACMAN_HOST
              value: "postgres-external"
            - name: DB_PACMAN_PORT
              value: "5432"
            - name: DB_PACMAN_NAME
              valueFrom:
                configMapKeyRef:
                  name: esq-config
                  key: POSTGRES_DB
            - name: DB_PACMAN_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: esq-config
                  key: POSTGRES_USER
            - name: DB_PACMAN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esq-secrets
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: pacman
  namespace: esquire
spec:
  selector:
    app: pacman
  ports:
    - port: 3004
      targetPort: 3004
